### ISSUE TITLE
Playback of video has gray bars top and bottom

### ISSUE THREAD

**Issue by jussisolja** [jonas-coded/netflix_hd_patch#1]
Love the work you are doing on this! Using it on Lenovo Tab 4 10 Plus and the app runs great in HD!

There is just one little bug I've found. Not sure you want to / have time to work on this but I'd appreciate it a lot!

When I'm playing a widescreen video there are light gray bars at the top and bottom of the screen. Not on top of the video but on the black area of the screen. It's not prohibiting use but it's slightly annoying and a fix would be greatly appreciated.

Also if you're up for it the Prime Video app had the same HD block issue so a fix for that would be amazing :)

Thanks!

**Comment by en00x** [comment]
+1

**Comment by jonas-coded** [comment]
Hi jussisolja,

I'm glad the patch works for you! I see on my Samsung Galaxy Tab 10.1 (2016) that the video borders are brighter than the normal black the screen can show, but it's not annoying to me so I would like to see if these are brighter on your's so a Screenshot would be nice. I also haven't looked yet if that's a thing I can easily fix but I can take a look. 

Regarding the Prime Video App, I also have the HD issue but the Apktool modified APK, without any code changes, isn't accepted by the Android System so I'm looking for the issue and waiting for an update that maybe fixes the problem.

**Comment by jussisolja** [comment]
Hey¡

Amazing thanks so much for the response! Screenshot here (sorry for the quality Netflix on my tablet didn't let me take a screenshot so had to take a pic) https://drive.google.com/file/d/1UxzGOok0OnTeJ21bCEwpLIvdZvt5L4Tp/view?usp=drivesdk
Hope that helps! Again can live with it but if it's not a big fix then would be great :)

Amazon...amazing - fingers crossed that could be fixed too. Annoying that they treat paying customers like this... Thanks again for the work on this!

**Comment by jonas-coded** [comment]
Little update here, so the color of the gray bars on your tablet is the same I see on mine. I may also have found the position in the resource files of the app, but unfortunately once decompiled Apktool can't re-compile the files because of some errors. At the moment I can't promise a fix but I look further into it.

**Comment by jussisolja** [comment]
Ok cool! Thanks so much for taking the time especially when it's not an issue that bugs you personally. Really appreciate it!

**Comment by jussisolja** [comment]
Hiya! Any progress on these? Would love the help as I can't code personally so totally helpless re this. The Prime app would be stellar to get. Happy to also compensate you for the work :)

**Comment by jonas-coded** [comment]
Hi! So regarding the bars I'm not able to change anything at the moment because I can't change the resource files containing the information without corrupting the app package. Regarding the Prime app, there's a new release for the Apktool so I will look if I can do something about it.
