### ISSUE TITLE
5.6 error 

### ISSUE THREAD

**Issue by CarlosSSC** [jonas-coded/netflix_hd_patch#10]
Every time I try to watch anything a message appears stating that there was a problem playing the video 
![Screenshot_20210927_160214_com netflix mediaclient](https://user-images.githubusercontent.com/80538989/134991669-e1829d02-b5dc-4ea0-9718-9772935d065d.jpg)

**Comment by jonas-coded** [comment]
Dear @CarlosSSC ,

I have discontinued supporting this repository. Because I also have never seen this error before, I can not give you any advice in solving the problem. I suspect that the Netflix App is no longer supported by Netflix and therefore can't play any videos anymore.

**Comment by ytrezq** [comment]
@jonas-coded : no the NetFlix ᴀᴘᴋ is still in the Android Play store and updated.
