### ISSUE TITLE
Plays HD. But unable to download. Button missing. 

### ISSUE THREAD

**Issue by Aniketts** [jonas-coded/netflix_hd_patch#2]
Plays HD. But unable to download. Button missing. 
![Screenshot_20190912-132841_Netflix](https://user-images.githubusercontent.com/55231016/64765443-c4189480-d561-11e9-8342-4c30241584a1.jpg)

**Comment by Aniketts** [comment]
@jonas-coded, please help resolve this issue. Device is SM t580.

**Comment by jonas-coded** [comment]
Hi @Aniketts ,
due to the fact that I am using the same device I've also come across this issue. I will have a look at the issue and whether it can be resolved or not. Please be patient or use the official Netflix app if you need to download content at the moment.

**Comment by jonas-coded** [comment]
The issue was resolved with version **4.13.0** . (Commit 8be81837b5370aa9310d49f57d5d62d43a44159b )

**Comment by Aniketts** [comment]
> Hi @Aniketts ,
> due to the fact that I am using the same device I've also come across this issue. I will have a look at the issue and whether it can be resolved or not. Please be patient or use the official Netflix app if you need to download content at the moment.

Thanks @jonas-coded for your support and good work. Atleast our devices has HD playback now.. :)
Any luck doing the same for prime videos though? God bless.

**Comment by Aniketts** [comment]
@jonas-coded any luck with getting HD for prime videos for sm-t580? Cheers!

**Comment by jonas-coded** [comment]
> @jonas-coded any luck with getting HD for prime videos for sm-t580? Cheers!

Hi @Aniketts , I'm sorry but at the current point I'm not able to activate HD on the Prime Video App. This is due to the fact that the app asks for some shared Amazon information (e.g. you are automatically logged in if you have the Amazon app installed) which is only given if the app's signature matches, which is not the case because if I modify the app I can only sign it with my own signature.

**Comment by Aniketts** [comment]
@jonas-coded, good day. Thanks for writing back. Is there some way I can share my signature with you for the Amazon app? And see if that works.

**Comment by jonas-coded** [comment]
> @jonas-coded, good day. Thanks for writing back. Is there some way I can share my signature with you for the Amazon app? And see if that works.

Hi @Aniketts , unfortunately this is not how it works. To modify the Amazon or Prime Video app I have to know **Amazon's signature**. This however is only known by Amazon's developers and is kept secret.

**Comment by Aniketts** [comment]
Gotcha.. Thanks @jonas-coded. :)
