### ISSUE TITLE
Anrdoid TV version

### ISSUE THREAD

**Issue by scropion86** [jonas-coded/netflix_hd_patch#3]
hi
i noticed that the available versions is regular andro APK modded , what a bout Android TVcompatible version an plan to have it.

regards,

**Comment by jonas-coded** [comment]
Hi @scropion86 ,
as far as I know there are no issues with playing Netflix content in HD on Android TV devices. If you could supply your device name and Widevine Level I will look into it.

Regards,
Jonas

**Comment by scropion86** [comment]
i have [Mecool KM9 Pro Deluxe ](https://www.aliexpress.com/item/32965400093.html?spm=a2g0o.productlist.0.0.772e1834vlsB5M&algo_pvid=d4b09ec9-fd1f-42fe-b2be-4fbbb3b95621&algo_expid=d4b09ec9-fd1f-42fe-b2be-4fbbb3b95621-0&btsid=c551b83c-af4e-47bd-a3be-3aec58d8d615&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_52) it is Google Certified and has Android TV 9.0 , 32Gb ,4G RAM , Chrome cast enabled , and Widevine Level L1

but once i download Netflix app from google Play it gives error that is not compatible with the device
and not even open the App interface.

i also downloaded a modded Android TV APK version it opens and logged in but once i start ant video it gives the same error

**Comment by jonas-coded** [comment]
Hi @scropion86 ,
I am sorry that you can't use the Netflix App on your device. Unfortunately, as my versions are only slightly modified versions of the official Netflix App, I can't offer you a version that is compatible with your device.

Also note that the product description of your device states that Netflix in HD is not available:
![image](https://user-images.githubusercontent.com/32209938/66301227-0205a000-e8f7-11e9-8428-33817eb53eaa.png)

**Comment by scropion86** [comment]
i know and that is clear thank you , but what i am looking for is to find a way to make Netflix official app from play store run normal even in SD quality.

by the way if i install mobile version it works on SD quality but here i have to use mouse as the mobile version is expecting a touch input not remote inputs as in Android TV version.

any way thanks for your replay

**Comment by jonas-coded** [comment]
@scropion86 I see your problem there, but what I am doing is just a patched Netflix App for HD so I can't help you with running the normal App on your device.
