### ISSUE TITLE
S8+ L3 work this apk?

### ISSUE THREAD

**Issue by saqie1393** [jonas-coded/netflix_hd_patch#4]
kindly suggest this version of apk work on s8+ oreo L3  HD possible ?

**Comment by jonas-coded** [comment]
Hi @saqie1393 ,
I'm very sorry, but this project is not aiming to enable Netflix HD on level 3 devices. Please note, that you have to get an L1 device to use this app. Also, a modification for L3 would require larger changes on the original Netflix app and might not work at all.
