### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by ghost** [jonas-coded/netflix_hd_patch#5]
This patch isn't working anymore, Netflix now seems to be blocking acess to any version bellow 5. When you select something it plays for a few seconds and then it stops and you get the error 0013.

Version 5 and above force you to update the app to continue using it. I tried installing the official unmodded 4.13.0 app and the same error happens, so the problem isn't the patch. This only started happening about a week ago. 

I have an a5 2017. Supports L1 but is not supported by Netflix. I tried installing a port of the s9+ rom that is supported in the official app but i also get an error (a different one, don't remember what it was) when i try to play something. So I'm kind of out of options here and i was hoping you could help.

**Comment by jonas-coded** [comment]
Hi @hemfreitas11,
thanks for your hint. I am using the modified 4.13.0 on my tablet myself and it is still working at the moment. Can you make sure that it is not your devices fault (e.g. test the network). If it's still not working please be so kind and provide the short device information of the Netflix App (Menu > Info > Device) so I can have a look.

**Comment by ghost** [comment]
Thanks for the quick reply, here it is:
![Screenshot_20200205-151336_Netflix](https://user-images.githubusercontent.com/42589445/73870179-5c255c00-482a-11ea-8cc1-4c53845131f6.jpg)
![Screenshot_20200205-151410_Netflix](https://user-images.githubusercontent.com/42589445/73870187-63e50080-482a-11ea-8e5f-13608c56c8c5.jpg)
I ran this network test a few times and the server 1 seems to not work sometimes, server 2 never works. Worked fine with the official updated app:
![Screenshot_20200205-152122_Netflix](https://user-images.githubusercontent.com/42589445/73871007-c8ed2600-482b-11ea-8d61-f212de5a52ac.jpg)
![Screenshot_20200205-152218_Netflix](https://user-images.githubusercontent.com/42589445/73871024-d2768e00-482b-11ea-9fa0-60ff30f80a39.jpg)

**Comment by jonas-coded** [comment]
Hi @hemfreitas11 ,
thanks for the information. Can you please confirm with a screenshot from DRM Info (https://play.google.com/store/apps/details?id=com.androidfung.drminfo&hl=en_US) that your device has Widevine Level L1.

**Comment by ghost** [comment]
DRM Info: 
![Screenshot_20200205-153419_DRM Info](https://user-images.githubusercontent.com/42589445/73871855-5ed58080-482d-11ea-865a-0193300cb3ce.jpg)
Playback specifications from the updated Netflix app:
![Screenshot_20200205-153621_Netflix](https://user-images.githubusercontent.com/42589445/73871943-80cf0300-482d-11ea-9a30-18ae27f31e98.jpg)

**Comment by jonas-coded** [comment]
Hi @hemfreitas11,
thank you very much! According to this data the patched app should work fine with your device. Could you please wait for 1-2 days and try in meantime to see if it's a Netflix server problem. Also you can ask the Netflix support if there are any problems or maintenances. I'm sorry that I couldn't help you yet.

**Comment by ghost** [comment]
Ok, thanks for the suggestion, i will contact them and see if thats the problem.

**Comment by ghost** [comment]
So i talked with them and they said there was nothing wrong on their part, but also sugested that i tried with a different network but still no luck.
I have reflashed the stock rom, tried installing another custom rom and nothing really works, i have no idea what could be the problem since you say it still works for you. Guess i will just have to wait to see if it comes back.

**Comment by ghost** [comment]
Hey so after trying a lot of stuff i finally managed to make it work again. I got another phone and connected it on the same network and installed your modded app. The app and that network test worked just fine on that other phone while still not working on mine. So with this test pretty much confirmed that the problem was indeed with my phone. Since i had already tried different roms and different networks the only thing left was the bootloader and the recovery. Today i flashed the stock ones again and sure enough, it is working again. So it seems that you can't use this mod with an unlocked bootloader and a custom recovery then.

**Comment by jonas-coded** [comment]
Hi @hemfreitas11,
I'm glad you could resolve the problem. My guess is that the unlocked bootloader and custom rom disabled the necessary Widevine Security Level in some way or another.
