### ISSUE TITLE
Capped at 480p

### ISSUE THREAD

**Issue by card0z** [jonas-coded/netflix_hd_patch#7]
For some reason, it doesn't go higher than 480p. Any tips?

**Comment by jonas-coded** [comment]
Hi @card0z,
of course I will try to help you with that. But first I need some information about your device.
Please attach a screenshot of the device info from the Netflix app (Menu > Info > Device).
Also please attach a screenshot of the DRM Info (https://play.google.com/store/apps/details?id=com.androidfung.drminfo&hl=en_US) of your device so we can make sure your device can use Widevine Level 1.

**Comment by card0z** [comment]
![Screenshot_20200826-112053750](https://user-images.githubusercontent.com/70178197/91264449-4065b100-e78e-11ea-917e-400fa2ab93bd.jpg)
![Screenshot_20200826-112037760](https://user-images.githubusercontent.com/70178197/91264486-42c80b00-e78e-11ea-8c25-3d215b92af12.jpg)
![Screenshot_20200826-112028797](https://user-images.githubusercontent.com/70178197/91264493-4360a180-e78e-11ea-8097-1bc5452a742c.jpg)


It has gone to Widevine level 3 because I have unlocked my bootloader. But the devices supports L1

**Comment by jonas-coded** [comment]
Hi @card0z,
I'm very sorry but I can't help you in that case. Using the app on rooted / unlocked devices doesn't work if the Widevine Level is degraded. Your device supports Widevine Level 1 only with original software, so the modificated app can't get you HD anymore.
